name: Gradle Build
on:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        required: true
        default: true
        description: 'release. true is release and false is SNAPSHOT.'
      release_name:
        description: 'github release name. such as 2.9.3 or 3.0.0-SNAPSHOT'
        required: true
      tag_name:
        description: 'github tag name. usually it is the same as the release_name'
        required: true
  push: null
  pull_request: null

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        name: Setup Java 25
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Get latest hash
        run: echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build
        env:
          BUILD_ID: ${{ github.run_number }}
          BUILD_RELEASE: ${{ inputs.release }}
      
      #      - name: Upload artifacts
      #        uses: actions/upload-artifact@v4
      #        with:
      #          name: sources-artifacts
      #          path: versions/*/build/libs/

      - name: Collect mod jars
        run: |
          shopt -s extglob
          mkdir mod-jars
          for jar in versions/*/build/libs/!(*-@(dev|sources|shadow)).jar; do
              cp -p "$jar" mod-jars/
          done
          ls -l mod-jars

      # This is the artifact recommended for users to download
      - name: Upload mod jars
        uses: actions/upload-artifact@v4
        with:
          name: quickshulker-${{ env.COMMIT_HASH }}
          path: mod-jars/*.jar

      - name: Release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          files: mod-jars/*.jar
          tag_name: ${{ github.event.inputs.tag_name }}